# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('direccion_cliente', models.CharField(blank=True, max_length=100, verbose_name='Dirección')),
                ('telefono_cliente', models.CharField(blank=True, max_length=100, verbose_name='Telefono')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('RFC', models.CharField(blank=True, max_length=25, verbose_name='RFC del Cliente')),
                ('importe_pesos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Importe en Pesos (MXN)')),
                ('importe_dolares', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Importe en Dolares (USD)')),
            ],
        ),
        migrations.CreateModel(
            name='HojaParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(blank=True, max_length=100, verbose_name='Concepto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad')),
                ('reparacion', models.CharField(blank=True, max_length=100, verbose_name='Reparación')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico_Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mecanico', models.DateTimeField(blank=True, max_length=100, verbose_name='Nombre del Mecanico Responsable')),
                ('direccion_mecanico', models.CharField(blank=True, max_length=100, verbose_name='Dirección del Mecanico Responsable')),
                ('telefono_mecanico', models.CharField(blank=True, max_length=100, verbose_name='Telefono Mecanico Responsable')),
                ('cost_x_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo Por Hora')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repuesto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Repuesto')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción de la Refacción')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo Unitario de la Refacción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo Unitario de la Refacción')),
                ('importe_parcial', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Importe')),
                ('hoja_parte', models.ManyToManyField(blank=True, to='core.HojaParte')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mecanico', models.ManyToManyField(blank=True, to='core.Mecanico_Responsable')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matricula del Vehiculo')),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Modelo del Vehiculo')),
                ('color_vehiculo', models.CharField(blank=True, max_length=100, verbose_name='Color del Vehiculo')),
                ('fecha_entrada_vehiculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrada del Vehiculo')),
                ('cliente_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='responsable',
            name='vehiculo',
            field=models.ManyToManyField(blank=True, to='core.Vehiculo'),
        ),
        migrations.AddField(
            model_name='hojaparte',
            name='mecanico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mecanico_Responsable'),
        ),
        migrations.AddField(
            model_name='hojaparte',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='hoja_parte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.HojaParte'),
        ),
        migrations.AddField(
            model_name='factura',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
