# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecanico_responsable',
            name='nombre_mecanico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Mecanico Responsable'),
        ),
    ]
